#!/bin/sh

# TODO: Fix absolute paths.
../utilities/santorini-cards-linux/bin/run --cards Apollo Pan     ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
../utilities/santorini-cards-linux/bin/run --cards Artemis Pan    ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
../utilities/santorini-cards-linux/bin/run --cards Atlas Pan      ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
../utilities/santorini-cards-linux/bin/run --cards Demeter Pan    ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
../utilities/santorini-cards-linux/bin/run --cards Hephastus Pan  ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
../utilities/santorini-cards-linux/bin/run --cards Minotaur Pan   ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
../utilities/santorini-cards-linux/bin/run --cards Pan Minotaur   ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
../utilities/santorini-cards-linux/bin/run --cards Prometheus Pan ../utilities/santorini-cards-linux/bin/play-random ../bin/santorini
